openwrt/docker

Dockerfile.imagebuilder
Dockerfile.sdk

Python3 is now a requirement for the buildroot and must therefore exist
in the sdk/imagebuilder containers.
Also sorted the package list and added myself as maintainer.

Dockerfile: install python3

---

.circleci/config.yml

While the pull requests already did so, the regular containers lacked
the signify-openbsd tool.

fixup: install signify-openbsd

---

docker-build.sh
docker-rootfs.sh

ImagBuilder and SDK use a different Dockerfile than the rootfs, this was
missed while refactoring for GitLab.

fixup: rootfs uses a different Dockerfile

---

docker-rootfs.sh

Initially the rootfs would only support snapshot builds as the stable
18.06.x wouldn't support Docker due to procd limitations. This was fixed
and therefore 19.07.x should also be supported.

fixup: support other branches for rootfs

---

docker-common.sh

This makes more sense as local users wouldn't use this function anyway.

docker-common: remove login as it's done by CI

---

docker-common.sh
docker-download.sh

This prevents mixing of keys when running the scripts locally for
testing, the same is done for the using keys.

use GNUHOME to use ./gpg

---

README.md

The former test instance of fe80.eu is no longer used, instead the
gitlab.com server run the scripts.

Update CI badge after move to gitlab.com

---

docker-rootfs.sh
docker-sdk.sh

previously multiple targets were combined in a single job so failing
targets should not stop others from being deployed. However as there are
now single builds per target this is no longer required.

replace true with exit when download fails

---

docker-download.sh

to make shellcheck happy we can no longer use glob, so now the script
use find to get the actual filename.

use find to replace previous glob behaviour

---

docker-download.sh

-printf is apperently not always available

fixup find -printf

---

.gitlab/ci/base.yml

This was removed during debugging and accidently forgotten to readd. It
fails to pass if no Docker credentials are given, which would be always
the case except on openwrtorg/master. In the future a test docker hub
account should be used instead of disabling it.

readd docker login on deploy

---

.gitlab-ci.yml

This was changed without fully thinking on it and should obviously be
corrected.

set pre-build as first stage again

---

docker-common.sh

Without the key verification may fail as both usign and pgp is used when
signatures are available.

docker-common: add 18.06 usign key

---

.gitlab/ci/imagebuilder.yml

That check is currently failing due to x86 image generation code
refactoring which changed naming of resulting images.
ls: cannot access './bin/targets/x86/64/*combined-squashfs.img.gz': No such file or directory
Fixes #48
Signed-off-by: Petr Štetiar <ynezz@true.cz>

ci: fix imagebuilder test for x86/64

---

docker-build.sh

I'm using Docker version 17.05.0-ce (don't ask me why), and it works fine to build the images except for this small issue.

docker-build: Fix compatibility with older Docker versions

---

.gitlab/ci/sdk.yml

This tries to fix failing CIs when files are not found which should have
been there.

sdk: run syncs and sleeps between IO intense steps

---

docker-common.sh
docker-download.sh

This allows to overwrite GNUPGHOME and USIGNHOME for local testing.

allow defining of key folder variable

---

.gitlab/ci/imagebuilder.yml

That check is currently failing due to different x86 image generation
code refactoring which changed naming of resulting images so they're now
different in master squashfs-combined Vs combined-squashfs in 19.07.
Signed-off-by: Petr Štetiar <ynezz@true.cz>

ci: fix imagebuilder test for 19.07 as well

---

.gitlab-ci.yml
.gitlab/ci/base.yml
.gitlab/ci/imagebuilder.yml
.gitlab/ci/rootfs.yml
.gitlab/ci/sdk.yml
README.md
docker-build.sh
docker-imagebuilder.sh
docker-rootfs.sh
docker-sdk.sh

The generate_targets.sh script requires to run on a specific branch to
only generate jobs for existing targets. The BRANCH variable was however
used for VERSION rather than the branch running on.
This changes the behaviour by automatically selecting the correct branch
and only taking the new VERSION env variable into account.
By doing so new Docker container tags include `snapshot` rather than
`master`, however for compatibility with existing setups the `master`
tag is still added.

replace BRANCH with VERSION

---

docker-sdk.sh

This should provide useful information in the CI logs for bisect
purposes etc. Otherwise its not possible to find out which version was
used, just the CI job timestamp.
Signed-off-by: Petr Štetiar <ynezz@true.cz>

docker-sdk: print out SDK revision

---

.gitlab/ci/deploy.yml

Using the "latest" tag in `Dockerfile.deploy` recently updated to Docker
20.x which changed the default behaviour of `docker push`. It now
requires `--all-tags` to push all tags, unlike before in 19.x.

chore: docker "latest" requires new flag

---

.github/workflows/containers.yml

* Set the platforms argument to docker/build-push-action.
* Insert a minimal *is it runable* test in between building and pushing the rootfs images.
* <s>Disable building rootfs for malta/be mips_24kc due to the images being unrunable (see https://github.com/openwrt/docker/issues/112#issuecomment-1519099490).</s> Not any more - they're working now.
Fixes #112.

Fix multiarch rootfs containers being mislabelled as AMD64.

---

.github/workflows/containers.yml

Instead of using a definied list with an if condition, use a case statement with wildcards to match on either `armsr` or `armvirt` (legacy). This should keep support for both 23.05.x and newer releases.

CI: add armsr, better debug output, actually skip skipped steps

---

.github/workflows/containers.yml
README.md

* Rename "master" to "main" (but continue to accept "master" for manual releases and add "master" suffixed tags)
* Add target/arch tags (no suffix) for snapshot images
* Add "latest" tag for x86_64 snapshot sdk
* Skip GitHub container registry login for imagebuilder/rootfs for pull requests
* Fix typos ("relase" to "release")
* Add daily builds for 23.05
* Change 22.03 builds to Tuesdays
* Change 21.02 builds from weekly to monthly
I don't know the exact buildbot schedules for 22.03 and 21.02 snapshots so the build scheduling here may have room for improvement.

Branch updates

---

.github/workflows/containers.yml

Some targets don't create a rootfs. Don't fail in those cases.

don't fail on empty rootfs

---

.github/workflows/containers.yml

Previously the container would use downloads.openwrt.org aka mirror-02 which has a short delay on images. This would break webhooks since they fire one ready on mirror-01 while not yet fully transferred to mirror-02.

use mirror-01 as filehost

---

.github/workflows/containers.yml

Instead of a schedule can cause a delay of up to 24h for snapshots, use a scripts that polls the buildbots and trigger specific versions and targets whenever a build is done.

disable schedule

---

.github/workflows/containers.yml

If the target name is a substring of another (e.g. malta/be and malta/be64), pushing the current target image will mistakenly override the other one.
Fixes #142
example broken action: https://github.com/openwrt/docker/actions/runs/10017123606

ci: use whole word matching for TARGET_FILTER

---

.github/workflows/containers.yml

Our CI is often heavily overloaded by CI testing jobs, however those Docker containers shouldn't be delayed by multiple hours. Let's have our own builder that does nothing but uploading those containers in time.

ci: run on docker-builder

---

README.md

fixes #148
As @ynezz noticed, SDKs with the missing tags are actually present, so add them to the doc.

Update README.md: add missing SDK tags

---

Dockerfile

Fixes https://github.com/openwrt/gh-action-sdk/issues/43
Disclaimer: This is just a reminder to update the base image and I didn't verify if everything is still working

update base image to buildworker 3.11.8

---

.github/workflows/containers.yml

Currently the Push stage fails for rootfs containers:
ERROR: failed to solve: process "/bin/sh -c if [ \"$RUN_SETUP\" -eq 1 ]; then /builder/setup.sh; fi" did not complete successfully: unable to find user root: invalid argument
This is happening as the commit 9999f3c7e58 ("Dockerfile: fix rootfs container generation") changed the file argument on Build stage, but Push stage was omitted.
So lets fix it now by using working Dockerfile.rootfs.
References: https://github.com/openwrt/docker/actions/runs/14235351624/job/39893588545#step:11:288
Fixes: 79999f3c7e58 ("Dockerfile: fix rootfs container generation")
Fixes: 9b55784b18f8 ("BREAKING: use setup.sh instead of Dockerfile")

ci: fix rootfs container push

---

.github/workflows/containers.yml

Currently the Smoke test stage fails in the push event pipeline:
```shell
Run docker run --platform=linux/mips_24kc sha256:d1700df716390394450d4851555b1904fd245c02e79573f6e97b4c24cdaafc8d uname -m
exec /bin/uname: exec format error
Error: Process completed with exit code 255.
```
This is not failing in the pull_request pipeline as the QEMU is properly configured. So lets fix the push event pipeline by configuring the QEMU in the same way, so the smoke test can pass.
Fixes: 3724e26fa114 ("ci: only use apt during testing")

ci: fix rootfs container smoke test during push

---

.github/workflows/containers.yml

Eric reported, that he is having problem with
imagebuilder:mediatek-filogic-master. The issue is caused by refactoring of Build Push stage in commit cda8065dc5d8 ("ci: add smoke testing of SDK and IB containers"), where I forget to enable pushing with `push: true` input as the default is `push: false`.
So lets fix it by explicitly enabling the push input, while at it unify the Push stage configs.
Fixes: #167
Fixes: cda8065dc5d8 ("ci: add smoke testing of SDK and IB containers")
Link: https://github.com/openwrt/docker/pull/168
Reported-by: Eric Fahlgren <ericfahlgren@gmail.com>

ci: fix pushing of ImageBuilder containers

---

setup.sh

This hides the download progress but is still more verbose then quiet.
This should help not to pollute the logs when downloading the sdk or imagebuilder with progress info.

setup.sh: less verbose wget output
